### PR TITLE
Start Firefox in Modern Kiosk mode (Full Screen Mode - Issue #6)

### PR DESCRIPTION
**Pull request by hecaxmmx**
Start Firefox in Kiosk mode.
Ability to start Firefox in Modern Kiosk mode, but no command line options (issue #6).
Command line option can be supplied by startup programs in whichever OS or batch/bash scripts process.

To test:
1) Package the extension.
2) Run the Nightly or Developer Edition version of Firefox or
3) Follow steps in [Test permission requests page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Test_permission_requests#Observe_or_verify_install_time_permission_requests)
4) Install your extension
5) Go to ModernKiosk preferences
6) Change the option Start Firefox in Kiosk mode to "Enable"
7) Close and start Firefox againg.
8) Observe that Firefox start in Full Screen mode with the page pre-defined in url option.

Optional test (If don't want to package)
1) Make a new clone or download a zip (of the fork hecaxmmx:master) to test in a temporary installation
2) Change lines (extension/mk_bg.js) and save:
    fullscreen_enable: false, to "true"
    fullscreen_disable: true to "false"
2) Got to about:debugging and click in button "Load temporary add-on"
3) See that Firefox is launched in kiosk mode with page "example.org"

### CODE REVIEW

**Comment by snatarajan85** [comment]
Interesting and awesome work. May I know when it will be available in market place? Its works great with temporary addon in debugging. I am not quite sure to generate xpi file or package this extension to install in my Firefox. Any suggestions?

**Comment by snatarajan85** [comment]
I am able to successfully run this in my Firefox with your changes.  Its look like multiple Firefox versions are running and its also launching kiosk mode with default URL configured in preference page.  Is it possible to pass the URL from command line? Example: Firefox.exe www.google.com

**Comment by hecaxmmx** [comment]
Hi @snatarajan85 
>May I know when it will be available in market place?

I'm awating for @cpg to review the pull-request. He is the owner of this extension, and he is the only one who can update the extension in [AMO.](https://addons.mozilla.org/en-US/firefox/)

>Is it possible to pass the URL from command line?

1. Right now you can trick this line:
Line 100 of [mk_bg.js](https://github.com/racketlogger/ModernKiosk/blob/1e565093fdf2452d0971f4ac69b0c8198e026551/extension/mk_bg.js#L100):
    `kiosk_url: "http://example.org/"`

2. Change to your app url then install [web-ext.](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Getting_started_with_web-ext)
3. In batch or bash script (depend on your OS) goto /ModernKiosk/extension and run `web-ext run`

Regards

### Amending this comment:

Also follow the "Optional test" above to start in fullscreen mode

**Comment by snatarajan85** [comment]
Thanks for your response. Yes noticed that but my URL is not constant and it will change depends client.

**Comment by hecaxmmx** [comment]
> Thanks for your response. Yes noticed that but my URL is not constant and it will change depends client.

Then add this code at the end of file mk_bg.js:

`browser.windows.getAll().then((windowsArray) => {`
`  windowsArray.forEach((currentWindow) => {`
`    browser.windows.update(currentWindow.id, {state: "fullscreen"});`
`  });`
`});`

Next you only run in command line `firefox https://www.google.com`
Maybe at this point, the major code of this extension is obsolete unless you want to use the context menu option.
Another solution, maybe, is that you can install the following extensions:

- [Auto Fullscreen by tazeat](https://addons.mozilla.org/en-US/firefox/addon/autofullscreen/?src=search)

- [nocontextmenu by Callan Bryant](https://addons.mozilla.org/en-US/firefox/addon/nocontextmenu/)

Regards

PS: My purpose with this extension is to got all this in one place, even much better if we can add a keyboard for touch screens.

**Comment by hecaxmmx** [comment]
>Maybe at this point, the major code of this extension is obsolete unless you want to use the context menu option.

I like Modern Kiosk rather than other extensions because the kiosk is opened in full screen in panel mode, i.e., users cannot navigate across sites or they cannot type another url.

**Comment by cpg** [comment]
Should we also add some bits of documentation for new users along with this change?

If nothing else, the tips above should be elevated for people who are more sophisticated than the average typical user and want to use this in some production environment.

**Comment by hecaxmmx** [comment]
> Should we also add some bits of documentation for new users along with this change?
> 
> If nothing else, the tips above should be elevated for people who are more sophisticated than the average typical user and want to use this in some production environment.

You're right, Carlos.

Could you open the Wiki space for this extension?
There we can write down all sort of documentation to help others.

Regards.

**Comment by cpg** [comment]
Good idea. First page created. I assume you can just create some PR to get things in it? Feel free.

**Comment by nbroutin34** [comment]
Hello,
where can I find the zip or xpi file to install it please ?

**Comment by hecaxmmx** [comment]
Hi @nbroutin34 
Sorry for the delay to answer you
You can prepare your own package of this extension if you download a ZIP file:

1) Goto the [main page](https://github.com/racketlogger/ModernKiosk) of this repository and you will find the button "Clone or download", there you can download a ZIP file.
2) Uncompress the file and goto (in my case) Downloads/ModernKiosk-master/extension/
3) Open with a simple text editor the file "manifest.json"
4) Add this code at the bottom of file and save:
**Add a comma in the last close curly brace, e.g.  },** And paste the code below:
`"browser_specific_settings": {`
`  "gecko": {`
`    "id": "addon@example.com",`
`    "strict_min_version": "42.0"`
`  }`
`}`
5) Install web-ext following this [guide](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Getting_started_with_web-ext#Installation)
6) Run `web-ext build` in the same folder above, this will create a folder web-ext-artifacts with a zip file inside.
7) Or you can follow this [guide](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Package_your_extension_) for the creation of a package too.
8) In Firefox Nightly goto "about:config" and search for "xpinstall.signatures.required" and change value to "false".
**NOTE: In some version of Firefox ESR you can override this configuration, see [here.](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct#w_what-are-my-options-if-i-want-to-use-an-unsigned-add-on-advanced-users) In my case Linux Debian 9 with Firefox 60.7.0esr (64-bit) Firefox Quantum extended support release, I can change this preference**
9) Goto "about:addons" or Ctrl-Shift-A and search for a "Gear" button, and the option "Install Add-on From File..."

And that's it, enjoy the extension whit the new changes!

Regards
**PS: You can ask personally to @cpg (Carlos) to update version and send to official Firefox Add-ons site. He is the only one can perform this task.**

TODO: This remind me that this kind of info can be placed in the Wiki.

**Comment by cpg** [comment]
@hecaxmmx .. the wiki is enabled, so you (or anyone else) can start adding content to it

**Comment by cpg** [comment]
[added to the wiki](https://github.com/racketlogger/ModernKiosk/wiki/How-to-prepare-your-own-package-of-this-extension)

**Comment by hecaxmmx** [comment]
Great job @cpg !

**Pull request merged**
